#!/usr/bin/env python3
"""Render a session-tail ingestion script.

Many agent frameworks (OpenClaw, Mastra, custom runtimes) write per-session
JSONL files containing the complete conversation history — model calls,
tool results, assistant responses, token usage, latency, etc.

This renderer generates a standalone Python script that:

1. ``tail -f`` the JSONL file (or glob pattern) for new lines
2. Parses each JSON line and maps fields to the observability schema
3. POSTs each event as an OTLP log to the OTLP HTTP bridge

This is **Layer 1 — zero-code injection**: the agent writes its native JSONL
as usual; the tail script runs alongside and ships data to ES. No code change
in the agent.

Bundle layout::

    session-tail/
    ├── session_tail.py      # The generated tail script
    ├── field_map.json       # Configurable field mapping
    └── README.md            # Usage guide

Usage:
    python render_session_tail.py \\
        --output-dir ./generated/session-tail \\
        --bridge-url http://localhost:14319 \\
        --session-dir /path/to/agent/sessions
"""

from __future__ import annotations

import argparse
from pathlib import Path

from common import SkillError, ensure_dir, print_error, write_text


_SESSION_TAIL_SCRIPT = '''\
#!/usr/bin/env python3
"""Auto-generated session JSONL tail → OTLP bridge ingester.

Watches a directory for JSONL session files and streams new lines to the
OTLP HTTP bridge as observability events. Zero changes needed in the agent.

Generated by: elasticsearch-agent-observability
"""

from __future__ import annotations

import argparse
import glob
import hashlib
import json
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib import error, request


BRIDGE_URL = os.environ.get("BRIDGE_URL", "{bridge_url}")
SESSION_DIR = os.environ.get("SESSION_DIR", "{session_dir}")
SESSION_GLOB = os.environ.get("SESSION_GLOB", "{session_glob}")
POLL_INTERVAL = float(os.environ.get("POLL_INTERVAL", "1.0"))
SERVICE_NAME = os.environ.get("OTEL_SERVICE_NAME", "{service_name}")

# Default field mapping: source JSONL key → target schema key.
# Override by editing field_map.json or setting FIELD_MAP_FILE env var.
DEFAULT_FIELD_MAP = {{
    # model / tokens
    "model": "gen_ai.request.model",
    "model_name": "gen_ai.request.model",
    "response_model": "gen_ai.response.model",
    "input_tokens": "gen_ai.usage.input_tokens",
    "output_tokens": "gen_ai.usage.output_tokens",
    "prompt_tokens": "gen_ai.usage.input_tokens",
    "completion_tokens": "gen_ai.usage.output_tokens",
    "total_tokens": "gen_ai.usage.total_tokens",
    # latency
    "latency_ms": "gen_ai.agent_ext.latency_ms",
    "duration_ms": "gen_ai.agent_ext.latency_ms",
    "duration": "gen_ai.agent_ext.latency_ms",
    # session / agent
    "session_id": "gen_ai.conversation.id",
    "conversation_id": "gen_ai.conversation.id",
    "thread_id": "gen_ai.conversation.id",
    "agent_id": "gen_ai.agent.id",
    "agent_name": "gen_ai.agent.name",
    "run_id": "gen_ai.agent.id",
    # tool
    "tool_name": "gen_ai.tool.name",
    "tool": "gen_ai.tool.name",
    "function_name": "gen_ai.tool.name",
    "tool_call_id": "gen_ai.tool.call.id",
    # role / action
    "role": "event.action",
    "type": "event.action",
    "action": "event.action",
    # error
    "error": "error.type",
    "error_type": "error.type",
    # status
    "status": "event.outcome",
    "success": "event.outcome",
}}


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _timestamp_to_unix_nano(value: Any) -> int | None:
    """Convert common timestamp shapes to Unix nanoseconds."""
    if value is None:
        return None
    if isinstance(value, (int, float)):
        number = float(value)
        # Heuristics: ns > 1e17, ms > 1e11, else seconds.
        if number > 1e17:
            return int(number)
        if number > 1e11:
            return int(number * 1_000_000)
        if number > 1e9:
            return int(number * 1_000_000_000)
        return None
    text = str(value).strip()
    if not text:
        return None
    if text.isdigit():
        return _timestamp_to_unix_nano(int(text))
    try:
        normalized = text.replace("Z", "+00:00")
        dt = datetime.fromisoformat(normalized)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return int(dt.timestamp() * 1_000_000_000)
    except ValueError:
        return None


def _load_field_map() -> dict[str, str]:
    map_file = os.environ.get("FIELD_MAP_FILE", "")
    if map_file and Path(map_file).exists():
        with open(map_file) as f:
            return json.load(f)
    # Try sibling field_map.json
    sibling = Path(__file__).parent / "field_map.json"
    if sibling.exists():
        with open(sibling) as f:
            return json.load(f)
    return DEFAULT_FIELD_MAP


def _extract_nested(data: dict, dotted_key: str) -> Any:
    """Extract a value from nested dict using dotted key notation."""
    parts = dotted_key.split(".")
    current = data
    for part in parts:
        if isinstance(current, dict):
            current = current.get(part)
        else:
            return None
    return current


def _map_record(record: dict[str, Any], field_map: dict[str, str]) -> dict[str, Any]:
    """Map a raw JSONL record to the observability schema."""
    doc: dict[str, Any] = {{
        "@timestamp": _now_iso(),
        "event.kind": "event",
        "event.category": "process",
        "service.name": SERVICE_NAME,
        "observer.ingest_path": "session_tail",
        "observer.type": "file_tail",
    }}

    # Try to extract timestamp from the record
    for ts_key in ("timestamp", "created_at", "time", "@timestamp", "ts"):
        ts_val = record.get(ts_key) or _extract_nested(record, ts_key)
        if ts_val:
            doc["@timestamp"] = str(ts_val)
            break

    # Apply field mapping
    for src_key, dst_key in field_map.items():
        value = record.get(src_key)
        if value is None:
            # Try dotted notation extraction
            value = _extract_nested(record, src_key)
        if value is None:
            continue
        if dst_key in doc:
            continue  # Don't overwrite already-set values

        # Special handling for boolean success → event.outcome
        if dst_key == "event.outcome" and isinstance(value, bool):
            doc[dst_key] = "success" if value else "failure"
        elif dst_key == "event.outcome" and isinstance(value, str):
            low = value.lower()
            if low in ("success", "ok", "pass", "true"):
                doc[dst_key] = "success"
            elif low in ("failure", "fail", "error", "false"):
                doc[dst_key] = "failure"
            else:
                doc[dst_key] = value
        else:
            doc[dst_key] = value

    # Auto-derive component_type from role
    role = record.get("role") or record.get("type") or ""
    if isinstance(role, str):
        role_lower = role.lower()
        if role_lower in ("assistant", "model", "llm"):
            doc.setdefault("gen_ai.agent_ext.component_type", "llm")
            doc.setdefault("gen_ai.operation.name", "chat")
        elif role_lower in ("tool", "function", "tool_result"):
            doc.setdefault("gen_ai.agent_ext.component_type", "tool")
            doc.setdefault("gen_ai.operation.name", "tool_call")
        elif role_lower in ("system", "user"):
            doc.setdefault("gen_ai.agent_ext.component_type", "runtime")

    # Extract usage from nested objects (common in OpenAI-style responses)
    usage = record.get("usage")
    if isinstance(usage, dict):
        if usage.get("prompt_tokens") is not None:
            doc.setdefault("gen_ai.usage.input_tokens", usage["prompt_tokens"])
        if usage.get("input_tokens") is not None:
            doc.setdefault("gen_ai.usage.input_tokens", usage["input_tokens"])
        if usage.get("completion_tokens") is not None:
            doc.setdefault("gen_ai.usage.output_tokens", usage["completion_tokens"])
        if usage.get("output_tokens") is not None:
            doc.setdefault("gen_ai.usage.output_tokens", usage["output_tokens"])
        if usage.get("total_tokens") is not None:
            doc.setdefault("gen_ai.usage.total_tokens", usage["total_tokens"])

    # Fallback: set event.outcome if not yet determined
    if "event.outcome" not in doc:
        doc["event.outcome"] = "failure" if doc.get("error.type") else "success"

    # Include raw content as message (truncated)
    content = record.get("content") or record.get("text") or record.get("message")
    if isinstance(content, str) and content:
        doc["message"] = content[:500]

    return doc


def _build_otlp_log(document: dict[str, Any]) -> dict[str, Any]:
    """Wrap a flat document into an OTLP/HTTP JSON log payload."""
    observed_ns = str(int(time.time() * 1_000_000_000))
    event_ns = _timestamp_to_unix_nano(document.get("@timestamp")) or int(observed_ns)
    body_text = document.get("message", "session_tail event")
    stable_hash = hashlib.sha256(json.dumps(document, sort_keys=True, ensure_ascii=False).encode("utf-8")).hexdigest()
    attributes = [{{"key": "event.hash", "value": {{"stringValue": stable_hash}}}}]
    for key, value in document.items():
        if key in ("@timestamp", "message"):
            continue
        if isinstance(value, bool):
            attributes.append({{"key": key, "value": {{"boolValue": value}}}})
        elif isinstance(value, int):
            attributes.append({{"key": key, "value": {{"intValue": str(value)}}}})
        elif isinstance(value, float):
            attributes.append({{"key": key, "value": {{"doubleValue": value}}}})
        elif value is not None:
            attributes.append({{"key": key, "value": {{"stringValue": str(value)}}}})
    return {{
        "resourceLogs": [{{
            "resource": {{
                "attributes": [
                    {{"key": "service.name", "value": {{"stringValue": SERVICE_NAME}}}},
                    {{"key": "observer.product", "value": {{"stringValue": "elasticsearch-agent-observability"}}}},
                ]
            }},
            "scopeLogs": [{{
                "scope": {{"name": "session-tail"}},
                "logRecords": [{{
                    "timeUnixNano": str(event_ns),
                    "observedTimeUnixNano": observed_ns,
                    "severityNumber": 9,
                    "severityText": "INFO",
                    "body": {{"stringValue": str(body_text)}},
                    "attributes": attributes,
                }}],
            }}],
        }}]
    }}


def _post_to_bridge(payload: dict[str, Any], bridge_url: str) -> bool:
    """POST an OTLP log payload to the bridge. Returns True on success."""
    endpoint = f"{{bridge_url.rstrip('/')}}/v1/logs"
    data = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    req = request.Request(endpoint, data=data, method="POST")
    req.add_header("Content-Type", "application/json")
    try:
        with request.urlopen(req, timeout=10) as resp:
            return resp.status in (200, 201)
    except (error.HTTPError, error.URLError, OSError) as exc:
        print(f"[session-tail] bridge POST failed: {{exc}}", file=sys.stderr)
        return False


class SessionTailer:
    """Watches JSONL files in a directory, tailing new lines and emitting to bridge."""

    def __init__(
        self,
        session_dir: str,
        pattern: str,
        field_map: dict[str, str],
        bridge_url: str,
        state_file: str,
        from_end: bool,
    ):
        self.session_dir = session_dir
        self.pattern = pattern
        self.field_map = field_map
        self.bridge_url = bridge_url
        self.state_file = Path(state_file)
        self.from_end = from_end
        self._state: dict[str, dict[str, int]] = self._load_state()
        self._emitted = 0
        self._errors = 0

    def _load_state(self) -> dict[str, dict[str, int]]:
        try:
            if self.state_file.exists():
                data = json.loads(self.state_file.read_text(encoding="utf-8"))
                if isinstance(data, dict):
                    return data.get("files", {{}}) if isinstance(data.get("files"), dict) else {{}}
        except (OSError, json.JSONDecodeError):
            pass
        return {{}}

    def _save_state(self) -> None:
        try:
            self.state_file.parent.mkdir(parents=True, exist_ok=True)
            payload = {{"files": self._state, "updated_at": _now_iso()}}
            self.state_file.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
        except OSError as exc:
            print(f"[session-tail] failed to persist state: {{exc}}", file=sys.stderr)

    def _discover_files(self) -> list[str]:
        full_pattern = os.path.join(self.session_dir, self.pattern)
        return sorted(glob.glob(full_pattern, recursive=True))

    def _tail_file(self, filepath: str) -> list[tuple[dict[str, Any] | None, int]]:
        records: list[tuple[dict[str, Any] | None, int]] = []
        try:
            stat = os.stat(filepath)
            size = stat.st_size
            inode = int(stat.st_ino)
        except OSError:
            return records

        key = str(Path(filepath).resolve())
        entry = self._state.get(key, {{}})
        last_pos = int(entry.get("offset", 0) or 0)
        last_inode = int(entry.get("inode", inode) or inode)
        if key not in self._state and self.from_end:
            self._state[key] = {{"inode": inode, "offset": size}}
            self._save_state()
            return records
        if inode != last_inode or size < last_pos:
            # File was rotated or truncated — re-read from start.
            last_pos = 0
        if size == last_pos:
            return records

        try:
            with open(filepath, "r", encoding="utf-8", errors="replace") as f:
                f.seek(last_pos)
                while True:
                    line = f.readline()
                    if not line:
                        break
                    pos_after = f.tell()
                    stripped = line.strip()
                    if not stripped:
                        records.append((None, pos_after))
                        continue
                    try:
                        record = json.loads(stripped)
                        records.append((record if isinstance(record, dict) else None, pos_after))
                    except json.JSONDecodeError:
                        records.append((None, pos_after))
        except OSError:
            pass
        return records

    def poll_once(self) -> int:
        """Poll all matching files for new records. Returns count of emitted events."""
        count = 0
        for filepath in self._discover_files():
            records = self._tail_file(filepath)
            key = str(Path(filepath).resolve())
            try:
                inode = int(os.stat(filepath).st_ino)
            except OSError:
                continue
            for record, pos_after in records:
                if record is None:
                    self._state[key] = {{"inode": inode, "offset": pos_after}}
                    self._save_state()
                    continue
                doc = _map_record(record, self.field_map)
                # Try to infer session_id from filename if not in the record
                if "gen_ai.conversation.id" not in doc:
                    fname = Path(filepath).stem
                    doc["gen_ai.conversation.id"] = fname
                payload = _build_otlp_log(doc)
                if _post_to_bridge(payload, self.bridge_url):
                    self._state[key] = {{"inode": inode, "offset": pos_after}}
                    self._save_state()
                    count += 1
                    self._emitted += 1
                else:
                    self._errors += 1
                    break
        return count

    def run_forever(self) -> None:
        print(f"[session-tail] Watching {{self.session_dir}}/{{self.pattern}} → {{self.bridge_url}}")
        print(f"[session-tail] Poll interval: {{POLL_INTERVAL}}s")
        try:
            while True:
                n = self.poll_once()
                if n > 0:
                    print(f"[session-tail] Emitted {{n}} events (total: {{self._emitted}}, errors: {{self._errors}})")
                time.sleep(POLL_INTERVAL)
        except KeyboardInterrupt:
            print(f"\\n[session-tail] Stopped. Total emitted: {{self._emitted}}, errors: {{self._errors}}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Tail session JSONL files and emit to OTLP bridge")
    parser.add_argument("--session-dir", default=SESSION_DIR, help="Directory containing JSONL session files")
    parser.add_argument("--pattern", default=SESSION_GLOB, help="Glob pattern for session files")
    parser.add_argument("--bridge-url", default=BRIDGE_URL, help="OTLP HTTP bridge URL")
    parser.add_argument("--state-file", default=str(Path(__file__).parent / ".session_tail_state.json"), help="Persistent offset state file")
    parser.add_argument("--from-end", action="store_true", help="Start new files from EOF instead of backfilling from the beginning")
    parser.add_argument("--backfill", action="store_true", help="Start new files from the beginning (default)")
    parser.add_argument("--once", action="store_true", help="Run once and exit (don't tail)")
    args = parser.parse_args()

    field_map = _load_field_map()
    bridge = args.bridge_url
    from_end = args.from_end and not args.backfill
    tailer = SessionTailer(args.session_dir, args.pattern, field_map, bridge, args.state_file, from_end)

    if args.once:
        n = tailer.poll_once()
        print(f"[session-tail] Emitted {{n}} events")
        return 0

    tailer.run_forever()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


_DEFAULT_FIELD_MAP = {
    "model": "gen_ai.request.model",
    "model_name": "gen_ai.request.model",
    "response_model": "gen_ai.response.model",
    "input_tokens": "gen_ai.usage.input_tokens",
    "output_tokens": "gen_ai.usage.output_tokens",
    "prompt_tokens": "gen_ai.usage.input_tokens",
    "completion_tokens": "gen_ai.usage.output_tokens",
    "total_tokens": "gen_ai.usage.total_tokens",
    "latency_ms": "gen_ai.agent_ext.latency_ms",
    "duration_ms": "gen_ai.agent_ext.latency_ms",
    "session_id": "gen_ai.conversation.id",
    "conversation_id": "gen_ai.conversation.id",
    "thread_id": "gen_ai.conversation.id",
    "agent_id": "gen_ai.agent.id",
    "agent_name": "gen_ai.agent.name",
    "tool_name": "gen_ai.tool.name",
    "tool": "gen_ai.tool.name",
    "function_name": "gen_ai.tool.name",
    "role": "event.action",
    "type": "event.action",
    "error": "error.type",
    "error_type": "error.type",
    "status": "event.outcome",
    "success": "event.outcome",
}


_README = """\
# Session Tail — JSONL file → OTLP bridge

## What this solves

Your agent framework (OpenClaw, Mastra, custom runtime) writes per-session
JSONL files containing complete conversation data — model calls, tool results,
token usage, latency, etc. You want this data in Kibana without modifying the
agent's source code.

This script **tails** the JSONL files in real time and ships each record to the
OTLP HTTP bridge, which writes it to Elasticsearch. Zero code changes in the agent.

## Quick start

```bash
# Start the OTLP bridge first (if not running)
python generated/agent-otel-bridge.py &

# Start tailing session files
python session_tail.py \\
    --session-dir /path/to/agent/sessions \\
    --pattern "*.jsonl" \\
    --bridge-url http://localhost:{bridge_port} \\
    --from-end
```

Or via environment variables:

```bash
export SESSION_DIR=/path/to/agent/sessions
export SESSION_GLOB="*.jsonl"
export BRIDGE_URL=http://localhost:{bridge_port}
python session_tail.py
```

## Field mapping

The script maps common JSONL field names to the observability schema. Default
mapping is built in; customize by editing `field_map.json`:

```json
{{
  "model": "gen_ai.request.model",
  "input_tokens": "gen_ai.usage.input_tokens",
  "output_tokens": "gen_ai.usage.output_tokens",
  "latency_ms": "gen_ai.agent_ext.latency_ms",
  "session_id": "gen_ai.conversation.id"
}}
```

Set `FIELD_MAP_FILE=/path/to/custom_map.json` to use a custom mapping file.

## One-shot mode

To process existing files without tailing:

```bash
python session_tail.py --once --backfill --session-dir /path/to/sessions
```

Offsets are persisted in `.session_tail_state.json`. A record is committed only
after the bridge accepts it, so temporary bridge failures do not silently drop data.

## What you get in Kibana

Once the tail is running with real session data, the dashboard shows:

- **Model call latency** from actual timestamps in the JSONL
- **Token usage** per model (if the framework records `usage`)
- **Tool call distribution** (if the framework records tool names)
- **Session timeline** with events ordered by JSONL line sequence
- **Error rates** from any errors logged in the session file

## What this does NOT cover

Session JSONL files are written by the framework, so they typically don't include:

- **Reasoning trace** (why the agent chose a particular action)
- **Evaluation scores** (quality assessment of responses)
- **User feedback** (human satisfaction rating)

These require Layer 3 (active reporting). See SKILL.md for details.
"""


def render_session_tail_bundle(
    output_dir: Path,
    *,
    bridge_url: str = "http://localhost:14319",
    session_dir: str = "./sessions",
    session_glob: str = "*.jsonl",
    service_name: str = "agent-runtime",
    bridge_port: int = 14319,
) -> dict[str, Path]:
    import json as _json

    ensure_dir(output_dir)
    script_path = output_dir / "session_tail.py"
    field_map_path = output_dir / "field_map.json"
    readme_path = output_dir / "README.md"

    write_text(
        script_path,
        _SESSION_TAIL_SCRIPT.format(
            bridge_url=bridge_url,
            session_dir=session_dir,
            session_glob=session_glob,
            service_name=service_name,
        ),
    )
    write_text(
        field_map_path,
        _json.dumps(_DEFAULT_FIELD_MAP, indent=2, ensure_ascii=False) + "\n",
    )
    write_text(
        readme_path,
        _README.format(bridge_port=bridge_port),
    )
    return {
        "script": script_path,
        "field_map": field_map_path,
        "readme": readme_path,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate a session JSONL tail → OTLP bridge script")
    parser.add_argument("--output-dir", required=True, help="Target directory for the session-tail bundle")
    parser.add_argument("--bridge-url", default="http://localhost:14319", help="OTLP HTTP bridge URL")
    parser.add_argument("--session-dir", default="./sessions", help="Default directory for JSONL session files")
    parser.add_argument("--session-glob", default="*.jsonl", help="Glob pattern for session files")
    parser.add_argument("--service-name", default="agent-runtime", help="OTel service name")
    return parser.parse_args()


def main() -> int:
    try:
        args = parse_args()
        paths = render_session_tail_bundle(
            Path(args.output_dir).expanduser().resolve(),
            bridge_url=args.bridge_url,
            session_dir=args.session_dir,
            session_glob=args.session_glob,
            service_name=args.service_name,
        )
        for label, path in paths.items():
            print(f"✅ {label}: {path}")
        return 0
    except SkillError as exc:
        print_error(str(exc))
        return 1
    except Exception as exc:  # noqa: BLE001
        print_error(f"Failed to generate session tail bundle: {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
